### ISSUE TITLE
Identifier finders don't find `+myObject: Object`

### ISSUE THREAD

**Issue by BrettWitty** [alexispurslane/tads3-mode#4]
Due to the AWK regex `^\++\s+(\w+): .*$` it expects space between `+`s and the identifier name, which is not required in the TADS 3 template. So a bunch of contained objects might be left out if there isn't a space. Also you might have a space in between the identifier and the `:`.

Perhaps change to `^\++\s*(\w+): .*$` ?

**Comment by alexispurslane** [comment]
Ah shit yeah good idea!

**Comment by alexispurslane** [comment]
fixed
